/*
 * Copyright (c) 2015-2020 Vladimir Schneider <vladimir.schneider@gmail.com>, all rights reserved.
 *
 * This code is private property of the copyright holder and cannot be used without
 * having obtained a license or prior written permission of the copyright holder.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */
package com.vladsch.md.nav.util

// used to be Auto-generated test data from: /Users/vlad/src/MarkdownTest/Readme.md
class MarkdownTest__Readme_md {

    companion object {
        @JvmStatic
        fun data(): Collection<Array<Any?>> {
            val data = MarkdownTestRowGenerator()
                /* @formatter:off */
                /*           "fullPath"                                                   , "linkType"    , "linkText"                         , "linkRef"                                                                , "linkAnchor" , "linkTitle", "resolvesLocal"                                           , "resolvesExternal"                                    , "linkAddress"                                      , "remoteAddress", "uri"                                        , "multiResolve") */
                /*  0 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::WikiLinkRef , ""                                 , "Wiki Link"                                                              , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf())
                /*  1 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::WikiLinkRef , ""                                 , "Home"                                                                   , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("MarkdownTest.wiki/Home.md"))
                        .withInspection("ID_WIKI_LINK_NOT_IN_WIKI", Severity.ERROR, null, null, null)
                /*  2 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "not relative link"                , "https://notchecked"                                                     , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf())
                /*  3 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "not relative link"                , "http://notchecked"                                                      , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf())
                /*  4 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "not relative link"                , "ftp://notchecked"                                                       , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf())
                /*  5 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "not relative link"                , "mailto:test@notchecked"                                                 , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf())
                /*  6 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "not relative link with anchor"    , ""                                                                       , "not-checked", null       , "Readme.md"                                               , "Readme.md"                                           , "#not-checked"                                     , null           , "Readme.md#not-checked"                      , arrayOf())
                /*  7 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Missing Link"                     , "Missing-File"                                                           , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf())
                /*  8 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Non Wiki File"                    , "NonWikiFile.md"                                                         , null         , null       , "NonWikiFile.md"                                          , "NonWikiFile.md"                                      , "NonWikiFile.md"                                   , null           , "NonWikiFile.md"                             , arrayOf())
                /*  9 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Link to self"                     , "Readme.md"                                                              , null         , null       , "Readme.md"                                               , "Readme.md"                                           , "#"                                                , null           , "Readme.md#"                                 , arrayOf("GitHubIssues/Issue-46/webbeheer_package/bower_components/autoNumeric/autoNumeric-2.0/readme.md", "GitHubIssues/Issue-46/webbeheer_package/bower_components/autoNumeric/readme.md", "GitHubIssues/Issue-46/webbeheer_package/bower_components/bootstrap-datepicker/README.md", "GitHubIssues/Issue-46/webbeheer_package/bower_components/bootstrap-datepicker/docs/README.md", "GitHubIssues/Issue-46/webbeheer_package/bower_components/bootstrap-datepicker/tests/README.md", "GitHubIssues/Issue-46/webbeheer_package/bower_components/bootstrap-daterangepicker/README.md", "GitHubIssues/Issue-46/webbeheer_package/bower_components/bootstrap-modal/README.md", "GitHubIssues/Issue-46/webbeheer_package/bower_components/bootstrap-sass/README.md", "GitHubIssues/Issue-46/webbeheer_package/bower_components/bootstrap/README.md", "GitHubIssues/Issue-46/webbeheer_package/bower_components/cropper/README.md", "GitHubIssues/Issue-46/webbeheer_package/bower_components/eonasdan-bootstrap-datetimepicker/README.md", "Readme.md", "untitled/README.md"))
                /* 10 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Link to self"                     , "Readme.md"                                                              , "test"       , null       , "Readme.md"                                               , "Readme.md"                                           , "#test"                                            , null           , "Readme.md#test"                             , arrayOf("Readme.md"))
                /* 11 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Non Wiki File with anchor"        , "NonWikiFile.md"                                                         , "testing"    , null       , "NonWikiFile.md"                                          , "NonWikiFile.md"                                      , "NonWikiFile.md#testing"                           , null           , "NonWikiFile.md#testing"                     , arrayOf())
                /* 12 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Sub Directory VCS Nested File"    , "SubDirectory/NestedFile.md"                                             , null         , null       , "SubDirectory/NestedFile.md"                              , "SubDirectory/NestedFile.md"                          , "SubDirectory/NestedFile.md"                       , null           , "SubDirectory/NestedFile.md"                 , arrayOf())
                /* 13 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Sub Directory Non VCS Nested File", "SubDirectory/NonVcsNestedFile.md"                                       , null         , null       , "SubDirectory/NonVcsNestedFile.md"                        , null                                                  , "SubDirectory/NonVcsNestedFile.md"                 , null           , "SubDirectory/NonVcsNestedFile.md"           , arrayOf())
                        .withInspection("ID_TARGET_NOT_UNDER_VCS", Severity.WARNING, null, null, null)
                /* 14 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Non Wiki File"                    , "nonwikifile.md"                                                         , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("NonWikiFile.md"))
                        .withInspection("ID_CASE_MISMATCH", Severity.ERROR, "NonWikiFile.md", "https://github.com/vsch/MarkdownTest/NonWikiFile.md", "nonwikifile.md")
                /* 15 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Non Wiki File"                    , "NONWIKIFILE.md"                                                         , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("NonWikiFile.md"))
                        .withInspection("ID_CASE_MISMATCH", Severity.ERROR, "NonWikiFile.md", "https://github.com/vsch/MarkdownTest/NonWikiFile.md", "NONWIKIFILE.md")
                /* 16 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Sub Directory VCS Nested File"    , "subDirectory/NestedFile.md"                                             , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("SubDirectory/NestedFile.md"))
                        .withInspection("ID_CASE_MISMATCH", Severity.ERROR, "SubDirectory/NestedFile.md", "https://github.com/vsch/MarkdownTest/SubDirectory/NestedFile.md", null)
                /* 17 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Sub Directory Non Vcs Nested File", "subDirectory/NonVcsNestedFile.md"                                       , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("SubDirectory/NonVcsNestedFile.md"))
                        .withInspection("ID_CASE_MISMATCH", Severity.ERROR, "SubDirectory/NonVcsNestedFile.md", "https://github.com/vsch/MarkdownTest/SubDirectory/NonVcsNestedFile.md", null)
                        .withInspection("ID_TARGET_NOT_UNDER_VCS", Severity.WARNING, null, null, null)
                /* 18 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Anchor in Name"                   , "anchor-in-name"                                                         , "5"          , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("anchor-in-name#5.md", "MarkdownTest.wiki/anchor-in-name#5.md"))
                        .withInspection("ID_TARGET_NAME_HAS_ANCHOR", Severity.WARNING, null, null, "MarkdownTest.wiki/anchor-in-name5.md")
                /* 19 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Anchor in Name"                   , "anchor-in-name"                                                         , "5.md"       , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("anchor-in-name#5.md", "MarkdownTest.wiki/anchor-in-name#5.md"))
                        .withInspection("ID_TARGET_NAME_HAS_ANCHOR", Severity.WARNING, null, null, "MarkdownTest.wiki/anchor-in-name5.md")
                        .withInspection("ID_LINK_TARGETS_WIKI_HAS_EXT", Severity.WARNING, "../../wiki/anchor-in-name%235", "https://github.com/vsch/MarkdownTest/wiki/anchor-in-name%235", null)
                /* 20 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Anchor in Name"                   , "anchor-in-name%235.md"                                                  , null         , null       , "anchor-in-name#5.md"                                     , "anchor-in-name#5.md"                                 , "anchor-in-name%235.md"                            , null           , "anchor-in-name%235.md"                      , arrayOf("anchor-in-name#5.md", "MarkdownTest.wiki/anchor-in-name#5.md"))
                /* 21 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Anchor in Name"                   , "anchor-in-name%235.md"                                                  , "5"          , null       , "anchor-in-name#5.md"                                     , "anchor-in-name#5.md"                                 , "anchor-in-name%235.md#5"                          , null           , "anchor-in-name%235.md#5"                    , arrayOf("anchor-in-name#5.md"))
                /* 22 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::ImageLinkRef, "Translation Manager Screenshot"   , "../../wiki/images/ScreenShot_main.png"                                  , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf())
                /* 23 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "clone"                            , "github-windows://openRepo/https://github.com/kriasoft/react-starter-kit", null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf())
                /* 24 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "fork"                             , "https://github.com/kriasoft/react-starter-kit/fork"                     , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf())
                /* 25 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Non Wiki File"                    , "NonWikiFile"                                                            , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("NonWikiFile.md"))
                /* 26 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Sub Directory VCS Nested File"    , "SubDirectory/NestedFile"                                                , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("SubDirectory/NestedFile.md"))
                /* 27 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Non Wiki File"                    , "nonwikifile"                                                            , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("NonWikiFile.md"))
                /* 28 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Non Wiki File"                    , "NONWIKIFILe"                                                            , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("NonWikiFile.md"))
                /* 29 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Sub Directory VCS Nested File"    , "SubDirectory/NestedFile"                                                , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("SubDirectory/NestedFile.md"))
                /* 30 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Sub Directory Non Vcs Nested File", "SubDirectory/NonVcsNestedFile"                                          , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("SubDirectory/NonVcsNestedFile.md"))
                        .withInspection("ID_TARGET_NOT_UNDER_VCS", Severity.WARNING, null, null, null)
                /* 31 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Sub Directory Nested File"        , "NestedFile"                                                             , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("SubDirectory/NestedFile.md"))
                /* 32 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Graphs"                           , "../../graphs"                                                           , null         , null       , null                                                      , "https://github.com/vsch/MarkdownTest/graphs"         , null                                               , "../../graphs" , "https://github.com/vsch/MarkdownTest/graphs", arrayOf())
                /* 33 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Issues"                           , "../../issues"                                                           , null         , null       , null                                                      , "https://github.com/vsch/MarkdownTest/issues"         , null                                               , "../../issues" , "https://github.com/vsch/MarkdownTest/issues", arrayOf())
                /* 34 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Pulls"                            , "../../pulls"                                                            , null         , null       , null                                                      , "https://github.com/vsch/MarkdownTest/pulls"          , null                                               , "../../pulls"  , "https://github.com/vsch/MarkdownTest/pulls" , arrayOf())
                /* 35 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Pulse"                            , "../../pulse"                                                            , null         , null       , null                                                      , "https://github.com/vsch/MarkdownTest/pulse"          , null                                               , "../../pulse"  , "https://github.com/vsch/MarkdownTest/pulse" , arrayOf())
                /* 36 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Wiki"                             , "../../wiki"                                                             , null         , null       , "MarkdownTest.wiki/Home.md"                               , "MarkdownTest.wiki/Home.md"                           , "../../wiki"                                       , null           , "wiki"                                       , arrayOf())
                /* 37 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Wiki Home"                        , "../../wiki/Home"                                                        , null         , null       , "MarkdownTest.wiki/Home.md"                               , "MarkdownTest.wiki/Home.md"                           , "../../wiki"                                       , null           , "wiki"                                       , arrayOf())
                /* 38 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Wiki Home"                        , "../../wiki/Home"                                                        , "test"       , null       , "MarkdownTest.wiki/Home.md"                               , "MarkdownTest.wiki/Home.md"                           , "../../wiki#test"                                  , null           , "wiki#test"                                  , arrayOf())
                /* 39 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Wiki Home"                        , "../../wiki/normal-file"                                                 , null         , null       , "MarkdownTest.wiki/normal-file.md"                        , "MarkdownTest.wiki/normal-file.md"                    , "../../wiki/normal-file"                           , null           , "wiki/normal-file"                           , arrayOf())
                /* 40 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Wiki Home"                        , "../../wiki/normal-file"                                                 , "test"       , null       , "MarkdownTest.wiki/normal-file.md"                        , "MarkdownTest.wiki/normal-file.md"                    , "../../wiki/normal-file#test"                      , null           , "wiki/normal-file#test"                      , arrayOf())
                /* 41 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Wiki Home"                        , "../../wiki/SubDirectory/Home.md"                                        , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf())
                /* 42 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "wiki normal file"                 , "../../wiki/normal-file"                                                 , null         , null       , "MarkdownTest.wiki/normal-file.md"                        , "MarkdownTest.wiki/normal-file.md"                    , "../../wiki/normal-file"                           , null           , "wiki/normal-file"                           , arrayOf())
                /* 43 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "wiki normal file"                 , "../../wiki/In-Name"                                                     , null         , null       , "MarkdownTest.wiki/SubDirectory/In-Name.md"               , "MarkdownTest.wiki/SubDirectory/In-Name.md"           , "../../wiki/In-Name"                               , null           , "wiki/In-Name"                               , arrayOf())
                /* 44 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "wiki normal file"                 , "../../wiki/In-Name.md"                                                  , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("MarkdownTest.wiki/SubDirectory/In-Name.md"))
                        .withInspection("ID_LINK_TARGETS_WIKI_HAS_EXT", Severity.WARNING, "../../wiki/In-Name", "https://github.com/vsch/MarkdownTest/wiki/In-Name", null)
                /* 45 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "wiki normal file"                 , "../../wiki/SubDirectory/In-Name.md"                                     , null         , null       , "MarkdownTest.wiki/SubDirectory/In-Name.md"               , "MarkdownTest.wiki/SubDirectory/In-Name.md"           , "../../wiki/SubDirectory/In-Name.md"               , null           , "wiki/SubDirectory/In-Name.md"               , arrayOf())
                        .withInspection("ID_LINK_TARGETS_WIKI_HAS_EXT", Severity.WARNING, "../../wiki/In-Name", null, null)
                /* 46 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Anchor in Name"                   , "../../wiki/anchor-in-name"                                              , "5"          , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("MarkdownTest.wiki/anchor-in-name#5.md"))
                        .withInspection("ID_TARGET_NAME_HAS_ANCHOR", Severity.WARNING, null, null, "MarkdownTest.wiki/anchor-in-name5.md")
                /* 47 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Anchor in Name"                   , "../../wiki/anchor-in-name%235"                                          , null         , null       , "MarkdownTest.wiki/anchor-in-name#5.md"                   , "MarkdownTest.wiki/anchor-in-name#5.md"               , "../../wiki/anchor-in-name%235"                    , null           , "wiki/anchor-in-name%235"                    , arrayOf())
                /* 48 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "normal file"                      , "../../wiki/normal-file"                                                 , null         , null       , "MarkdownTest.wiki/normal-file.md"                        , "MarkdownTest.wiki/normal-file.md"                    , "../../wiki/normal-file"                           , null           , "wiki/normal-file"                           , arrayOf())
                /* 49 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "normal file"                      , "../../wiki/normal-file.md"                                              , null         , null       , "MarkdownTest.wiki/normal-file.md"                        , "MarkdownTest.wiki/normal-file.md"                    , "../../wiki/normal-file.md"                        , null           , "wiki/normal-file.md"                        , arrayOf())
                        .withInspection("ID_LINK_TARGETS_WIKI_HAS_EXT", Severity.WARNING, "../../wiki/normal-file", null, null)
                /* 50 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "wiki normal file"                 , "../../wiki/In-Name.md"                                                  , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("MarkdownTest.wiki/SubDirectory/In-Name.md"))
                        .withInspection("ID_LINK_TARGETS_WIKI_HAS_EXT", Severity.WARNING, "../../wiki/In-Name", null, null)
                /* 51 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "wiki normal file"                 , "../../wiki/SubDirectory/In-Name.md"                                     , null         , null       , "MarkdownTest.wiki/SubDirectory/In-Name.md"               , "MarkdownTest.wiki/SubDirectory/In-Name.md"           , "../../wiki/SubDirectory/In-Name.md"               , null           , "wiki/SubDirectory/In-Name.md"               , arrayOf())
                        .withInspection("ID_LINK_TARGETS_WIKI_HAS_EXT", Severity.WARNING, "../../wiki/In-Name", null, null)
                /* 52 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::ImageLinkRef, "vcs image"                        , "vcs-image.png"                                                          , null         , null       , "vcs-image.png"                                           , "vcs-image.png"                                       , "vcs-image.png"                                    , null           , "vcs-image.png"                              , arrayOf("vcs-image.png", "MarkdownTest.wiki/vcs-image.png"))
                /* 53 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::ImageLinkRef, "sub dir vcs image"                , "SubDirectory/sub-dir-vcs-image.png"                                     , null         , null       , "SubDirectory/sub-dir-vcs-image.png"                      , "SubDirectory/sub-dir-vcs-image.png"                  , "SubDirectory/sub-dir-vcs-image.png"               , null           , "SubDirectory/sub-dir-vcs-image.png"         , arrayOf())
                /* 54 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::ImageLinkRef, "non vcs image"                    , "non-vcs-image.png"                                                      , null         , null       , "non-vcs-image.png"                                       , null                                                  , "non-vcs-image.png"                                , null           , "non-vcs-image.png"                          , arrayOf("non-vcs-image.png", "MarkdownTest.wiki/non-vcs-image.png"))
                        .withInspection("ID_TARGET_NOT_UNDER_VCS", Severity.WARNING, null, null, null)
                /* 55 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::ImageLinkRef, "sub dir non vcs image"            , "SubDirectory/sub-dir-non-vcs-image.png"                                 , null         , null       , "SubDirectory/sub-dir-non-vcs-image.png"                  , null                                                  , "SubDirectory/sub-dir-non-vcs-image.png"           , null           , "SubDirectory/sub-dir-non-vcs-image.png"     , arrayOf())
                        .withInspection("ID_TARGET_NOT_UNDER_VCS", Severity.WARNING, null, null, null)
                /* 56 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::ImageLinkRef, "vcs image"                        , "../../wiki/vcs-image.png"                                               , null         , null       , "MarkdownTest.wiki/vcs-image.png"                         , "MarkdownTest.wiki/vcs-image.png"                     , "../../wiki/vcs-image.png"                         , null           , "wiki/vcs-image.png"                         , arrayOf())
                /* 57 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::ImageLinkRef, "sub dir vcs image"                , "../../wiki/SubDirectory/sub-dir-vcs-image.png"                          , null         , null       , "MarkdownTest.wiki/SubDirectory/sub-dir-vcs-image.png"    , "MarkdownTest.wiki/SubDirectory/sub-dir-vcs-image.png", "../../wiki/SubDirectory/sub-dir-vcs-image.png"    , null           , "wiki/SubDirectory/sub-dir-vcs-image.png"    , arrayOf())
                /* 58 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::ImageLinkRef, "non vcs image"                    , "../../wiki/non-vcs-image.png"                                           , null         , null       , "MarkdownTest.wiki/non-vcs-image.png"                     , null                                                  , "../../wiki/non-vcs-image.png"                     , null           , "wiki/non-vcs-image.png"                     , arrayOf())
                        .withInspection("ID_TARGET_NOT_UNDER_VCS", Severity.WARNING, null, null, null)
                /* 59 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::ImageLinkRef, "sub dir non vcs image"            , "../../wiki/SubDirectory/sub-dir-non-vcs-image.png"                      , null         , null       , "MarkdownTest.wiki/SubDirectory/sub-dir-non-vcs-image.png", null                                                  , "../../wiki/SubDirectory/sub-dir-non-vcs-image.png", null           , "wiki/SubDirectory/sub-dir-non-vcs-image.png", arrayOf())
                        .withInspection("ID_TARGET_NOT_UNDER_VCS", Severity.WARNING, null, null, null)
                /* 60 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Space In Name"                    , "../../wiki/Space%20In%20Name"                                           , null         , null       , "MarkdownTest.wiki/Space In Name.md"                      , "MarkdownTest.wiki/Space In Name.md"                  , "../../wiki/Space%20In%20Name"                     , null           , "wiki/Space%20In%20Name"                     , arrayOf())
                /* 61 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Space In Name"                    , "../../wiki/Space%20In%20Name"                                           , "anchor"     , null       , "MarkdownTest.wiki/Space In Name.md"                      , "MarkdownTest.wiki/Space In Name.md"                  , "../../wiki/Space%20In%20Name#anchor"              , null           , "wiki/Space%20In%20Name#anchor"              , arrayOf())
                /* 62 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Space Anchor In Name"             , "../../wiki/Space%20In%20Name%236"                                       , "anchor"     , null       , "MarkdownTest.wiki/Space In Name#6.md"                    , "MarkdownTest.wiki/Space In Name#6.md"                , "../../wiki/Space%20In%20Name%236#anchor"          , null           , "wiki/Space%20In%20Name%236#anchor"          , arrayOf())
                /* 63 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "../../wiki/Test.kt"               , "../../wiki/Test.kt"                                                     , null         , null       , "MarkdownTest.wiki/Test.kt"                               , "MarkdownTest.wiki/Test.kt"                           , "../../wiki/Test.kt"                               , null           , "wiki/Test.kt"                               , arrayOf())
                /* 64 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "../../wiki/test.kt"               , "../../wiki/test.kt"                                                     , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("MarkdownTest.wiki/Test.kt"))
                        .withInspection("ID_CASE_MISMATCH", Severity.ERROR, "../../wiki/Test.kt", "https://github.com/vsch/MarkdownTest/wiki/Test.kt", "MarkdownTest.wiki/test.kt")
                /* 65 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "../../wiki/normal-file.md"        , "../../wiki/normal-file.md"                                              , null         , null       , "MarkdownTest.wiki/normal-file.md"                        , "MarkdownTest.wiki/normal-file.md"                    , "../../wiki/normal-file.md"                        , null           , "wiki/normal-file.md"                        , arrayOf())
                        .withInspection("ID_LINK_TARGETS_WIKI_HAS_EXT", Severity.WARNING, "../../wiki/normal-file", null, null)
                /* 66 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "../../wiki/Normal-File.md"        , "../../wiki/Normal-File.md"                                              , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("MarkdownTest.wiki/normal-file.md"))
                        .withInspection("ID_CASE_MISMATCH", Severity.WEAK_WARNING, "../../wiki/normal-file.md", "https://github.com/vsch/MarkdownTest/wiki/normal-file.md", "MarkdownTest.wiki/Normal-File.md")
                        .withInspection("ID_LINK_TARGETS_WIKI_HAS_EXT", Severity.WARNING, "../../wiki/normal-file", "https://github.com/vsch/MarkdownTest/wiki/normal-file", null)
                /* 67 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "../../wiki/normal-file"           , "../../wiki/Normal-File"                                                 , null         , null       , "MarkdownTest.wiki/normal-file.md"                        , "MarkdownTest.wiki/normal-file.md"                    , "../../wiki/normal-file"                           , null           , "wiki/normal-file"                           , arrayOf())
                        .withInspection("ID_CASE_MISMATCH", Severity.WEAK_WARNING, "../../wiki/normal-file", "https://github.com/vsch/MarkdownTest/wiki/normal-file", "/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Normal-File.md")
                /* 68 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "Sub Directory VCS Nested File"    , "Subdirectory/nestedFile.md"                                             , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("SubDirectory/NestedFile.md"))
                        .withInspection("ID_CASE_MISMATCH", Severity.ERROR, "SubDirectory/NestedFile.md", "https://github.com/vsch/MarkdownTest/SubDirectory/NestedFile.md", null)
                /* 69 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "../../wiki/Test-Name.kt"          , "../../wiki/Test-Name.kt"                                                , null         , null       , "MarkdownTest.wiki/Test-Name.kt.md"                       , "MarkdownTest.wiki/Test-Name.kt.md"                   , "../../wiki/Test-Name.kt"                          , null           , "wiki/Test-Name.kt"                          , arrayOf("MarkdownTest.wiki/Test-Name.kt.md", "MarkdownTest.wiki/Test-Name.kt"))
                /* 70 */.row("/Users/vlad/src/MarkdownTest/SubDirectory/Multiple-Match.md", ::LinkRef     , "Sub Directory VCS Nested File"    , "Sub/NestedFile2.md"                                                     , null         , null       , "Sub/NestedFile2.md"                                      , "Sub/NestedFile2.md"                                  , "Sub/NestedFile2.md"                               , null           , "Sub/NestedFile2.md"                         , arrayOf())
                /* 71 */.row("/Users/vlad/src/MarkdownTest/SubDirectory/Multiple-Match.md", ::LinkRef     , "Sub Directory VCS Nested File"    , "/SubDirectory/Sub/NestedFile2.md"                                       , null         , null       , "Sub/NestedFile2.md"                                      , "Sub/NestedFile2.md"                                  , "Sub/NestedFile2.md"                               , null           , "Sub/NestedFile2.md"                         , arrayOf())
                /* 72 */.row("/Users/vlad/src/MarkdownTest/SubDirectory/Multiple-Match.md", ::LinkRef     , "Sub Directory VCS Nested File"    , "/blob/master/SubDirectory/Sub/NestedFile2.md"                           , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf("Sub/NestedFile2.md"))
                /* 73 */.row("/Users/vlad/src/MarkdownTest/single-link-test.md"           , ::LinkRef     , "single link test"                 , "single-link-test.md"                                                    , null         , null       , "single-link-test.md"                                     , "single-link-test.md"                                 , "#"                                                , null           , "single-link-test.md"                        , arrayOf("single-link-test.md", "MarkdownTest.wiki/single-link-test.md"))
                /* 74 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "/wiki/normal-file.md"             , "/wiki/normal-file.md"                                                   , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf())
                /* 75 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::LinkRef     , "wiki normal file"                 , "/../../wiki/normal-file"                                                , null         , null       , null                                                      , null                                                  , null                                               , null           , null                                         , arrayOf())
                /* 76 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::ImageLinkRef, "vcs image"                        , "/vcs-image.png"                                                         , null         , null       , "vcs-image.png"                                           , "vcs-image.png"                                       , "vcs-image.png"                                    , null           , "vcs-image.png"                              , arrayOf("vcs-image.png"))
                /* 77 */.row("/Users/vlad/src/MarkdownTest/Readme.md"                     , ::ImageLinkRef, "vcs image"                        , "/../../raw/master/vcs-image.png"                                        , null         , null       , "vcs-image.png"                                           , "vcs-image.png"                                       , "vcs-image.png"                                    , null           , "vcs-image.png"                              , arrayOf("vcs-image.png"))
                /* @formatter:on */
                .rows
            return data
        }
    }
}
