
package com.vladsch.idea.multimarkdown.util

import com.vladsch.idea.multimarkdown.printData
import org.pegdown.ast.*

// Auto-generated test data from: /Users/vlad/src/idea-multimarkdown2/src/test/java/com/vladsch/idea/multimarkdown/util/LexParser.md

class LexParser_md_RootNode {
    companion object {
        //@Parameterized.Parameters(name = "{index}: markdownInput = {0}, rootNode = {1}")
        @JvmStatic
        fun data(): Collection<Array<Any?>> {

            val cleanData = false
            val data = arrayListOf<Array<Any?>>(
                /* @formatter:off */
                /*      arrayOf<Any?>("markdownInput"                                  , "rootNode") */
                /*  0 */arrayOf<Any?>("[[ ]]"                                          , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(WikiLinkNode(" ").setRange(0, 5))).setRange(0, 5))).setRange(0, 5)), listOf(), listOf(), listOf()).setRange(0, 5)) /*  0 */,
                /*  1 */arrayOf<Any?>("[[#]]"                                          , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(WikiLinkNode("#").setRange(0, 5))).setRange(0, 5))).setRange(0, 5)), listOf(), listOf(), listOf()).setRange(0, 5)) /*  1 */,
                /*  2 */arrayOf<Any?>("[[#anchor]]"                                    , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(WikiLinkNode("#anchor").setRange(0, 11))).setRange(0, 11))).setRange(0, 11)), listOf(), listOf(), listOf()).setRange(0, 11)) /*  2 */,
                /*  3 */arrayOf<Any?>("[[WikiAddress]]"                                , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(WikiLinkNode("WikiAddress").setRange(0, 15))).setRange(0, 15))).setRange(0, 15)), listOf(), listOf(), listOf()).setRange(0, 15)) /*  3 */,
                /*  4 */arrayOf<Any?>("[[WikiAddress#anchor]]"                         , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(WikiLinkNode("WikiAddress#anchor").setRange(0, 22))).setRange(0, 22))).setRange(0, 22)), listOf(), listOf(), listOf()).setRange(0, 22)) /*  4 */,
                /*  5 */arrayOf<Any?>("[[Wiki Text|Wiki Address]]"                     , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(WikiLinkNode("Wiki Text|Wiki Address").setRange(0, 26))).setRange(0, 26))).setRange(0, 26)), listOf(), listOf(), listOf()).setRange(0, 26)) /*  5 */,
                /*  6 */arrayOf<Any?>("[[Wiki Text|Wiki Address#anchor]]"              , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(WikiLinkNode("Wiki Text|Wiki Address#anchor").setRange(0, 33))).setRange(0, 33))).setRange(0, 33)), listOf(), listOf(), listOf()).setRange(0, 33)) /*  6 */,
                /*  7 */arrayOf<Any?>("[ ]()"                                          , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 5))).setRange(0, 5))).setRange(0, 5)), listOf(), listOf(), listOf()).setRange(0, 5)) /*  7 */,
                /*  8 */arrayOf<Any?>("[ ]( )"                                         , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 6))).setRange(0, 6))).setRange(0, 6)), listOf(), listOf(), listOf()).setRange(0, 6)) /*  8 */,
                /*  9 */arrayOf<Any?>("[ ](#)"                                         , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "#", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 6))).setRange(0, 6))).setRange(0, 6)), listOf(), listOf(), listOf()).setRange(0, 6)) /*  9 */,
                /* 10 */arrayOf<Any?>("[ ](#anchor)"                                   , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "#anchor", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 12))).setRange(0, 12))).setRange(0, 12)), listOf(), listOf(), listOf()).setRange(0, 12)) /* 10 */,
                /* 11 */arrayOf<Any?>("[ ](link-address)"                              , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 17))).setRange(0, 17))).setRange(0, 17)), listOf(), listOf(), listOf()).setRange(0, 17)) /* 11 */,
                /* 12 */arrayOf<Any?>("[ ](link-address#)"                             , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 18))).setRange(0, 18))).setRange(0, 18)), listOf(), listOf(), listOf()).setRange(0, 18)) /* 12 */,
                /* 13 */arrayOf<Any?>("[ ](link-address#anchor)"                       , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#anchor", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 24))).setRange(0, 24))).setRange(0, 24)), listOf(), listOf(), listOf()).setRange(0, 24)) /* 13 */,
                /* 14 */arrayOf<Any?>("[link text](link-address)"                      , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address", SuperNode(listOf(TextNode("link text").setRange(1, 10))).setRange(0, 0)).setRange(0, 25))).setRange(0, 25))).setRange(0, 25)), listOf(), listOf(), listOf()).setRange(0, 25)) /* 14 */,
                /* 15 */arrayOf<Any?>("[link text](link-address#)"                     , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#", SuperNode(listOf(TextNode("link text").setRange(1, 10))).setRange(0, 0)).setRange(0, 26))).setRange(0, 26))).setRange(0, 26)), listOf(), listOf(), listOf()).setRange(0, 26)) /* 15 */,
                /* 16 */arrayOf<Any?>("[link text](link-address#anchor)"               , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#anchor", SuperNode(listOf(TextNode("link text").setRange(1, 10))).setRange(0, 0)).setRange(0, 32))).setRange(0, 32))).setRange(0, 32)), listOf(), listOf(), listOf()).setRange(0, 32)) /* 16 */,
                /* 17 */arrayOf<Any?>("[**link text**](link-address)"                  , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(3, 12)), "**", true, true).setRange(1, 14))).setRange(0, 0)).setRange(0, 29))).setRange(0, 29))).setRange(0, 29)), listOf(), listOf(), listOf()).setRange(0, 29)) /* 17 */,
                /* 18 */arrayOf<Any?>("[**link text**](link-address#)"                 , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(3, 12)), "**", true, true).setRange(1, 14))).setRange(0, 0)).setRange(0, 30))).setRange(0, 30))).setRange(0, 30)), listOf(), listOf(), listOf()).setRange(0, 30)) /* 18 */,
                /* 19 */arrayOf<Any?>("[**link text**](link-address#anchor)"           , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#anchor", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(3, 12)), "**", true, true).setRange(1, 14))).setRange(0, 0)).setRange(0, 36))).setRange(0, 36))).setRange(0, 36)), listOf(), listOf(), listOf()).setRange(0, 36)) /* 19 */,
                /* 20 */arrayOf<Any?>("[ ]() \"\""                                     , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 5), TextNode(" ").setRange(5, 6), SpecialTextNode(""").setRange(6, 7), SpecialTextNode(""").setRange(7, 8))).setRange(0, 8))).setRange(0, 8)), listOf(), listOf(), listOf()).setRange(0, 8)) /* 20 */,
                /* 21 */arrayOf<Any?>("[ ]( ) \"\""                                    , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 6), TextNode(" ").setRange(6, 7), SpecialTextNode(""").setRange(7, 8), SpecialTextNode(""").setRange(8, 9))).setRange(0, 9))).setRange(0, 9)), listOf(), listOf(), listOf()).setRange(0, 9)) /* 21 */,
                /* 22 */arrayOf<Any?>("[ ](#) \"\""                                    , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "#", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 6), TextNode(" ").setRange(6, 7), SpecialTextNode(""").setRange(7, 8), SpecialTextNode(""").setRange(8, 9))).setRange(0, 9))).setRange(0, 9)), listOf(), listOf(), listOf()).setRange(0, 9)) /* 22 */,
                /* 23 */arrayOf<Any?>("[ ](#anchor) \"\""                              , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "#anchor", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 12), TextNode(" ").setRange(12, 13), SpecialTextNode(""").setRange(13, 14), SpecialTextNode(""").setRange(14, 15))).setRange(0, 15))).setRange(0, 15)), listOf(), listOf(), listOf()).setRange(0, 15)) /* 23 */,
                /* 24 */arrayOf<Any?>("[ ](link-address) \"\""                         , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 17), TextNode(" ").setRange(17, 18), SpecialTextNode(""").setRange(18, 19), SpecialTextNode(""").setRange(19, 20))).setRange(0, 20))).setRange(0, 20)), listOf(), listOf(), listOf()).setRange(0, 20)) /* 24 */,
                /* 25 */arrayOf<Any?>("[ ](link-address#) \"\""                        , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 18), TextNode(" ").setRange(18, 19), SpecialTextNode(""").setRange(19, 20), SpecialTextNode(""").setRange(20, 21))).setRange(0, 21))).setRange(0, 21)), listOf(), listOf(), listOf()).setRange(0, 21)) /* 25 */,
                /* 26 */arrayOf<Any?>("[ ](link-address#anchor) \"\""                  , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#anchor", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 24), TextNode(" ").setRange(24, 25), SpecialTextNode(""").setRange(25, 26), SpecialTextNode(""").setRange(26, 27))).setRange(0, 27))).setRange(0, 27)), listOf(), listOf(), listOf()).setRange(0, 27)) /* 26 */,
                /* 27 */arrayOf<Any?>("[link text](link-address) \"\""                 , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address", SuperNode(listOf(TextNode("link text").setRange(1, 10))).setRange(0, 0)).setRange(0, 25), TextNode(" ").setRange(25, 26), SpecialTextNode(""").setRange(26, 27), SpecialTextNode(""").setRange(27, 28))).setRange(0, 28))).setRange(0, 28)), listOf(), listOf(), listOf()).setRange(0, 28)) /* 27 */,
                /* 28 */arrayOf<Any?>("[link text](link-address#) \"\""                , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#", SuperNode(listOf(TextNode("link text").setRange(1, 10))).setRange(0, 0)).setRange(0, 26), TextNode(" ").setRange(26, 27), SpecialTextNode(""").setRange(27, 28), SpecialTextNode(""").setRange(28, 29))).setRange(0, 29))).setRange(0, 29)), listOf(), listOf(), listOf()).setRange(0, 29)) /* 28 */,
                /* 29 */arrayOf<Any?>("[link text](link-address#anchor) \"\""          , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#anchor", SuperNode(listOf(TextNode("link text").setRange(1, 10))).setRange(0, 0)).setRange(0, 32), TextNode(" ").setRange(32, 33), SpecialTextNode(""").setRange(33, 34), SpecialTextNode(""").setRange(34, 35))).setRange(0, 35))).setRange(0, 35)), listOf(), listOf(), listOf()).setRange(0, 35)) /* 29 */,
                /* 30 */arrayOf<Any?>("[**link text**](link-address) \"\""             , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(3, 12)), "**", true, true).setRange(1, 14))).setRange(0, 0)).setRange(0, 29), TextNode(" ").setRange(29, 30), SpecialTextNode(""").setRange(30, 31), SpecialTextNode(""").setRange(31, 32))).setRange(0, 32))).setRange(0, 32)), listOf(), listOf(), listOf()).setRange(0, 32)) /* 30 */,
                /* 31 */arrayOf<Any?>("[**link text**](link-address#) \"\""            , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(3, 12)), "**", true, true).setRange(1, 14))).setRange(0, 0)).setRange(0, 30), TextNode(" ").setRange(30, 31), SpecialTextNode(""").setRange(31, 32), SpecialTextNode(""").setRange(32, 33))).setRange(0, 33))).setRange(0, 33)), listOf(), listOf(), listOf()).setRange(0, 33)) /* 31 */,
                /* 32 */arrayOf<Any?>("[**link text**](link-address#anchor) \"\""      , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#anchor", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(3, 12)), "**", true, true).setRange(1, 14))).setRange(0, 0)).setRange(0, 36), TextNode(" ").setRange(36, 37), SpecialTextNode(""").setRange(37, 38), SpecialTextNode(""").setRange(38, 39))).setRange(0, 39))).setRange(0, 39)), listOf(), listOf(), listOf()).setRange(0, 39)) /* 32 */,
                /* 33 */arrayOf<Any?>("[ ]() \"Title\""                                , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 5), TextNode(" ").setRange(5, 6), QuotedNode(listOf(TextNode("Title").setRange(7, 12)), QuotedNode.Type.Double).setRange(6, 13))).setRange(0, 13))).setRange(0, 13)), listOf(), listOf(), listOf()).setRange(0, 13)) /* 33 */,
                /* 34 */arrayOf<Any?>("[ ]( ) \"Title\""                               , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 6), TextNode(" ").setRange(6, 7), QuotedNode(listOf(TextNode("Title").setRange(8, 13)), QuotedNode.Type.Double).setRange(7, 14))).setRange(0, 14))).setRange(0, 14)), listOf(), listOf(), listOf()).setRange(0, 14)) /* 34 */,
                /* 35 */arrayOf<Any?>("[ ](#) \"Title\""                               , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "#", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 6), TextNode(" ").setRange(6, 7), QuotedNode(listOf(TextNode("Title").setRange(8, 13)), QuotedNode.Type.Double).setRange(7, 14))).setRange(0, 14))).setRange(0, 14)), listOf(), listOf(), listOf()).setRange(0, 14)) /* 35 */,
                /* 36 */arrayOf<Any?>("[ ](#anchor) \"Title\""                         , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "#anchor", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 12), TextNode(" ").setRange(12, 13), QuotedNode(listOf(TextNode("Title").setRange(14, 19)), QuotedNode.Type.Double).setRange(13, 20))).setRange(0, 20))).setRange(0, 20)), listOf(), listOf(), listOf()).setRange(0, 20)) /* 36 */,
                /* 37 */arrayOf<Any?>("[ ](link-address) \"Title\""                    , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 17), TextNode(" ").setRange(17, 18), QuotedNode(listOf(TextNode("Title").setRange(19, 24)), QuotedNode.Type.Double).setRange(18, 25))).setRange(0, 25))).setRange(0, 25)), listOf(), listOf(), listOf()).setRange(0, 25)) /* 37 */,
                /* 38 */arrayOf<Any?>("[ ](link-address#) \"Title\""                   , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 18), TextNode(" ").setRange(18, 19), QuotedNode(listOf(TextNode("Title").setRange(20, 25)), QuotedNode.Type.Double).setRange(19, 26))).setRange(0, 26))).setRange(0, 26)), listOf(), listOf(), listOf()).setRange(0, 26)) /* 38 */,
                /* 39 */arrayOf<Any?>("[ ](link-address#anchor) \"Title\""             , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#anchor", SuperNode(listOf(TextNode(" ").setRange(1, 2))).setRange(0, 0)).setRange(0, 24), TextNode(" ").setRange(24, 25), QuotedNode(listOf(TextNode("Title").setRange(26, 31)), QuotedNode.Type.Double).setRange(25, 32))).setRange(0, 32))).setRange(0, 32)), listOf(), listOf(), listOf()).setRange(0, 32)) /* 39 */,
                /* 40 */arrayOf<Any?>("[link text](link-address) \"Title\""            , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address", SuperNode(listOf(TextNode("link text").setRange(1, 10))).setRange(0, 0)).setRange(0, 25), TextNode(" ").setRange(25, 26), QuotedNode(listOf(TextNode("Title").setRange(27, 32)), QuotedNode.Type.Double).setRange(26, 33))).setRange(0, 33))).setRange(0, 33)), listOf(), listOf(), listOf()).setRange(0, 33)) /* 40 */,
                /* 41 */arrayOf<Any?>("[link text](link-address#) \"Title\""           , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#", SuperNode(listOf(TextNode("link text").setRange(1, 10))).setRange(0, 0)).setRange(0, 26), TextNode(" ").setRange(26, 27), QuotedNode(listOf(TextNode("Title").setRange(28, 33)), QuotedNode.Type.Double).setRange(27, 34))).setRange(0, 34))).setRange(0, 34)), listOf(), listOf(), listOf()).setRange(0, 34)) /* 41 */,
                /* 42 */arrayOf<Any?>("[link text](link-address#anchor) \"Title\""     , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#anchor", SuperNode(listOf(TextNode("link text").setRange(1, 10))).setRange(0, 0)).setRange(0, 32), TextNode(" ").setRange(32, 33), QuotedNode(listOf(TextNode("Title").setRange(34, 39)), QuotedNode.Type.Double).setRange(33, 40))).setRange(0, 40))).setRange(0, 40)), listOf(), listOf(), listOf()).setRange(0, 40)) /* 42 */,
                /* 43 */arrayOf<Any?>("[**link text**](link-address) \"Title\""        , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(3, 12)), "**", true, true).setRange(1, 14))).setRange(0, 0)).setRange(0, 29), TextNode(" ").setRange(29, 30), QuotedNode(listOf(TextNode("Title").setRange(31, 36)), QuotedNode.Type.Double).setRange(30, 37))).setRange(0, 37))).setRange(0, 37)), listOf(), listOf(), listOf()).setRange(0, 37)) /* 43 */,
                /* 44 */arrayOf<Any?>("[**link text**](link-address#) \"Title\""       , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(3, 12)), "**", true, true).setRange(1, 14))).setRange(0, 0)).setRange(0, 30), TextNode(" ").setRange(30, 31), QuotedNode(listOf(TextNode("Title").setRange(32, 37)), QuotedNode.Type.Double).setRange(31, 38))).setRange(0, 38))).setRange(0, 38)), listOf(), listOf(), listOf()).setRange(0, 38)) /* 44 */,
                /* 45 */arrayOf<Any?>("[**link text**](link-address#anchor) \"Title\"" , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpLinkNode("", "link-address#anchor", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(3, 12)), "**", true, true).setRange(1, 14))).setRange(0, 0)).setRange(0, 36), TextNode(" ").setRange(36, 37), QuotedNode(listOf(TextNode("Title").setRange(38, 43)), QuotedNode.Type.Double).setRange(37, 44))).setRange(0, 44))).setRange(0, 44)), listOf(), listOf(), listOf()).setRange(0, 44)) /* 45 */,
                /* 46 */arrayOf<Any?>("![ ]()"                                         , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 6))).setRange(0, 6))).setRange(0, 6)), listOf(), listOf(), listOf()).setRange(0, 6)) /* 46 */,
                /* 47 */arrayOf<Any?>("![ ]( )"                                        , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 7))).setRange(0, 7))).setRange(0, 7)), listOf(), listOf(), listOf()).setRange(0, 7)) /* 47 */,
                /* 48 */arrayOf<Any?>("![ ](#)"                                        , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "#", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 7))).setRange(0, 7))).setRange(0, 7)), listOf(), listOf(), listOf()).setRange(0, 7)) /* 48 */,
                /* 49 */arrayOf<Any?>("![ ](#anchor)"                                  , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "#anchor", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 13))).setRange(0, 13))).setRange(0, 13)), listOf(), listOf(), listOf()).setRange(0, 13)) /* 49 */,
                /* 50 */arrayOf<Any?>("![ ](link-address)"                             , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 18))).setRange(0, 18))).setRange(0, 18)), listOf(), listOf(), listOf()).setRange(0, 18)) /* 50 */,
                /* 51 */arrayOf<Any?>("![ ](link-address#)"                            , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 19))).setRange(0, 19))).setRange(0, 19)), listOf(), listOf(), listOf()).setRange(0, 19)) /* 51 */,
                /* 52 */arrayOf<Any?>("![ ](link-address#anchor)"                      , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#anchor", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 25))).setRange(0, 25))).setRange(0, 25)), listOf(), listOf(), listOf()).setRange(0, 25)) /* 52 */,
                /* 53 */arrayOf<Any?>("![link text](link-address)"                     , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address", SuperNode(listOf(TextNode("link text").setRange(2, 11))).setRange(0, 0)).setRange(0, 26))).setRange(0, 26))).setRange(0, 26)), listOf(), listOf(), listOf()).setRange(0, 26)) /* 53 */,
                /* 54 */arrayOf<Any?>("![link text](link-address#)"                    , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#", SuperNode(listOf(TextNode("link text").setRange(2, 11))).setRange(0, 0)).setRange(0, 27))).setRange(0, 27))).setRange(0, 27)), listOf(), listOf(), listOf()).setRange(0, 27)) /* 54 */,
                /* 55 */arrayOf<Any?>("![link text](link-address#anchor)"              , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#anchor", SuperNode(listOf(TextNode("link text").setRange(2, 11))).setRange(0, 0)).setRange(0, 33))).setRange(0, 33))).setRange(0, 33)), listOf(), listOf(), listOf()).setRange(0, 33)) /* 55 */,
                /* 56 */arrayOf<Any?>("![**link text**](link-address)"                 , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(4, 13)), "**", true, true).setRange(2, 15))).setRange(0, 0)).setRange(0, 30))).setRange(0, 30))).setRange(0, 30)), listOf(), listOf(), listOf()).setRange(0, 30)) /* 56 */,
                /* 57 */arrayOf<Any?>("![**link text**](link-address#)"                , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(4, 13)), "**", true, true).setRange(2, 15))).setRange(0, 0)).setRange(0, 31))).setRange(0, 31))).setRange(0, 31)), listOf(), listOf(), listOf()).setRange(0, 31)) /* 57 */,
                /* 58 */arrayOf<Any?>("![**link text**](link-address#anchor)"          , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#anchor", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(4, 13)), "**", true, true).setRange(2, 15))).setRange(0, 0)).setRange(0, 37))).setRange(0, 37))).setRange(0, 37)), listOf(), listOf(), listOf()).setRange(0, 37)) /* 58 */,
                /* 59 */arrayOf<Any?>("![ ]() \"\""                                    , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 6), TextNode(" ").setRange(6, 7), SpecialTextNode(""").setRange(7, 8), SpecialTextNode(""").setRange(8, 9))).setRange(0, 9))).setRange(0, 9)), listOf(), listOf(), listOf()).setRange(0, 9)) /* 59 */,
                /* 60 */arrayOf<Any?>("![ ]( ) \"\""                                   , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 7), TextNode(" ").setRange(7, 8), SpecialTextNode(""").setRange(8, 9), SpecialTextNode(""").setRange(9, 10))).setRange(0, 10))).setRange(0, 10)), listOf(), listOf(), listOf()).setRange(0, 10)) /* 60 */,
                /* 61 */arrayOf<Any?>("![ ](#) \"\""                                   , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "#", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 7), TextNode(" ").setRange(7, 8), SpecialTextNode(""").setRange(8, 9), SpecialTextNode(""").setRange(9, 10))).setRange(0, 10))).setRange(0, 10)), listOf(), listOf(), listOf()).setRange(0, 10)) /* 61 */,
                /* 62 */arrayOf<Any?>("![ ](#anchor) \"\""                             , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "#anchor", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 13), TextNode(" ").setRange(13, 14), SpecialTextNode(""").setRange(14, 15), SpecialTextNode(""").setRange(15, 16))).setRange(0, 16))).setRange(0, 16)), listOf(), listOf(), listOf()).setRange(0, 16)) /* 62 */,
                /* 63 */arrayOf<Any?>("![ ](link-address) \"\""                        , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 18), TextNode(" ").setRange(18, 19), SpecialTextNode(""").setRange(19, 20), SpecialTextNode(""").setRange(20, 21))).setRange(0, 21))).setRange(0, 21)), listOf(), listOf(), listOf()).setRange(0, 21)) /* 63 */,
                /* 64 */arrayOf<Any?>("![ ](link-address#) \"\""                       , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 19), TextNode(" ").setRange(19, 20), SpecialTextNode(""").setRange(20, 21), SpecialTextNode(""").setRange(21, 22))).setRange(0, 22))).setRange(0, 22)), listOf(), listOf(), listOf()).setRange(0, 22)) /* 64 */,
                /* 65 */arrayOf<Any?>("![ ](link-address#anchor) \"\""                 , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#anchor", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 25), TextNode(" ").setRange(25, 26), SpecialTextNode(""").setRange(26, 27), SpecialTextNode(""").setRange(27, 28))).setRange(0, 28))).setRange(0, 28)), listOf(), listOf(), listOf()).setRange(0, 28)) /* 65 */,
                /* 66 */arrayOf<Any?>("![link text](link-address) \"\""                , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address", SuperNode(listOf(TextNode("link text").setRange(2, 11))).setRange(0, 0)).setRange(0, 26), TextNode(" ").setRange(26, 27), SpecialTextNode(""").setRange(27, 28), SpecialTextNode(""").setRange(28, 29))).setRange(0, 29))).setRange(0, 29)), listOf(), listOf(), listOf()).setRange(0, 29)) /* 66 */,
                /* 67 */arrayOf<Any?>("![link text](link-address#) \"\""               , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#", SuperNode(listOf(TextNode("link text").setRange(2, 11))).setRange(0, 0)).setRange(0, 27), TextNode(" ").setRange(27, 28), SpecialTextNode(""").setRange(28, 29), SpecialTextNode(""").setRange(29, 30))).setRange(0, 30))).setRange(0, 30)), listOf(), listOf(), listOf()).setRange(0, 30)) /* 67 */,
                /* 68 */arrayOf<Any?>("![link text](link-address#anchor) \"\""         , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#anchor", SuperNode(listOf(TextNode("link text").setRange(2, 11))).setRange(0, 0)).setRange(0, 33), TextNode(" ").setRange(33, 34), SpecialTextNode(""").setRange(34, 35), SpecialTextNode(""").setRange(35, 36))).setRange(0, 36))).setRange(0, 36)), listOf(), listOf(), listOf()).setRange(0, 36)) /* 68 */,
                /* 69 */arrayOf<Any?>("![**link text**](link-address) \"\""            , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(4, 13)), "**", true, true).setRange(2, 15))).setRange(0, 0)).setRange(0, 30), TextNode(" ").setRange(30, 31), SpecialTextNode(""").setRange(31, 32), SpecialTextNode(""").setRange(32, 33))).setRange(0, 33))).setRange(0, 33)), listOf(), listOf(), listOf()).setRange(0, 33)) /* 69 */,
                /* 70 */arrayOf<Any?>("![**link text**](link-address#) \"\""           , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(4, 13)), "**", true, true).setRange(2, 15))).setRange(0, 0)).setRange(0, 31), TextNode(" ").setRange(31, 32), SpecialTextNode(""").setRange(32, 33), SpecialTextNode(""").setRange(33, 34))).setRange(0, 34))).setRange(0, 34)), listOf(), listOf(), listOf()).setRange(0, 34)) /* 70 */,
                /* 71 */arrayOf<Any?>("![**link text**](link-address#anchor) \"\""     , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#anchor", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(4, 13)), "**", true, true).setRange(2, 15))).setRange(0, 0)).setRange(0, 37), TextNode(" ").setRange(37, 38), SpecialTextNode(""").setRange(38, 39), SpecialTextNode(""").setRange(39, 40))).setRange(0, 40))).setRange(0, 40)), listOf(), listOf(), listOf()).setRange(0, 40)) /* 71 */,
                /* 72 */arrayOf<Any?>("![ ]() \"Title\""                               , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 6), TextNode(" ").setRange(6, 7), QuotedNode(listOf(TextNode("Title").setRange(8, 13)), QuotedNode.Type.Double).setRange(7, 14))).setRange(0, 14))).setRange(0, 14)), listOf(), listOf(), listOf()).setRange(0, 14)) /* 72 */,
                /* 73 */arrayOf<Any?>("![ ]( ) \"Title\""                              , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 7), TextNode(" ").setRange(7, 8), QuotedNode(listOf(TextNode("Title").setRange(9, 14)), QuotedNode.Type.Double).setRange(8, 15))).setRange(0, 15))).setRange(0, 15)), listOf(), listOf(), listOf()).setRange(0, 15)) /* 73 */,
                /* 74 */arrayOf<Any?>("![ ](#) \"Title\""                              , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "#", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 7), TextNode(" ").setRange(7, 8), QuotedNode(listOf(TextNode("Title").setRange(9, 14)), QuotedNode.Type.Double).setRange(8, 15))).setRange(0, 15))).setRange(0, 15)), listOf(), listOf(), listOf()).setRange(0, 15)) /* 74 */,
                /* 75 */arrayOf<Any?>("![ ](#anchor) \"Title\""                        , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "#anchor", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 13), TextNode(" ").setRange(13, 14), QuotedNode(listOf(TextNode("Title").setRange(15, 20)), QuotedNode.Type.Double).setRange(14, 21))).setRange(0, 21))).setRange(0, 21)), listOf(), listOf(), listOf()).setRange(0, 21)) /* 75 */,
                /* 76 */arrayOf<Any?>("![ ](link-address) \"Title\""                   , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 18), TextNode(" ").setRange(18, 19), QuotedNode(listOf(TextNode("Title").setRange(20, 25)), QuotedNode.Type.Double).setRange(19, 26))).setRange(0, 26))).setRange(0, 26)), listOf(), listOf(), listOf()).setRange(0, 26)) /* 76 */,
                /* 77 */arrayOf<Any?>("![ ](link-address#) \"Title\""                  , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 19), TextNode(" ").setRange(19, 20), QuotedNode(listOf(TextNode("Title").setRange(21, 26)), QuotedNode.Type.Double).setRange(20, 27))).setRange(0, 27))).setRange(0, 27)), listOf(), listOf(), listOf()).setRange(0, 27)) /* 77 */,
                /* 78 */arrayOf<Any?>("![ ](link-address#anchor) \"Title\""            , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#anchor", SuperNode(listOf(TextNode(" ").setRange(2, 3))).setRange(0, 0)).setRange(0, 25), TextNode(" ").setRange(25, 26), QuotedNode(listOf(TextNode("Title").setRange(27, 32)), QuotedNode.Type.Double).setRange(26, 33))).setRange(0, 33))).setRange(0, 33)), listOf(), listOf(), listOf()).setRange(0, 33)) /* 78 */,
                /* 79 */arrayOf<Any?>("![link text](link-address) \"Title\""           , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address", SuperNode(listOf(TextNode("link text").setRange(2, 11))).setRange(0, 0)).setRange(0, 26), TextNode(" ").setRange(26, 27), QuotedNode(listOf(TextNode("Title").setRange(28, 33)), QuotedNode.Type.Double).setRange(27, 34))).setRange(0, 34))).setRange(0, 34)), listOf(), listOf(), listOf()).setRange(0, 34)) /* 79 */,
                /* 80 */arrayOf<Any?>("![link text](link-address#) \"Title\""          , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#", SuperNode(listOf(TextNode("link text").setRange(2, 11))).setRange(0, 0)).setRange(0, 27), TextNode(" ").setRange(27, 28), QuotedNode(listOf(TextNode("Title").setRange(29, 34)), QuotedNode.Type.Double).setRange(28, 35))).setRange(0, 35))).setRange(0, 35)), listOf(), listOf(), listOf()).setRange(0, 35)) /* 80 */,
                /* 81 */arrayOf<Any?>("![link text](link-address#anchor) \"Title\""    , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#anchor", SuperNode(listOf(TextNode("link text").setRange(2, 11))).setRange(0, 0)).setRange(0, 33), TextNode(" ").setRange(33, 34), QuotedNode(listOf(TextNode("Title").setRange(35, 40)), QuotedNode.Type.Double).setRange(34, 41))).setRange(0, 41))).setRange(0, 41)), listOf(), listOf(), listOf()).setRange(0, 41)) /* 81 */,
                /* 82 */arrayOf<Any?>("![**link text**](link-address) \"Title\""       , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(4, 13)), "**", true, true).setRange(2, 15))).setRange(0, 0)).setRange(0, 30), TextNode(" ").setRange(30, 31), QuotedNode(listOf(TextNode("Title").setRange(32, 37)), QuotedNode.Type.Double).setRange(31, 38))).setRange(0, 38))).setRange(0, 38)), listOf(), listOf(), listOf()).setRange(0, 38)) /* 82 */,
                /* 83 */arrayOf<Any?>("![**link text**](link-address#) \"Title\""      , RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(4, 13)), "**", true, true).setRange(2, 15))).setRange(0, 0)).setRange(0, 31), TextNode(" ").setRange(31, 32), QuotedNode(listOf(TextNode("Title").setRange(33, 38)), QuotedNode.Type.Double).setRange(32, 39))).setRange(0, 39))).setRange(0, 39)), listOf(), listOf(), listOf()).setRange(0, 39)) /* 83 */,
                /* 84 */arrayOf<Any?>("![**link text**](link-address#anchor) \"Title\"", RootNode(listOf(ParaNode(listOf(SuperNode(listOf(ExpImageNode("", "link-address#anchor", SuperNode(listOf(StrongEmphSuperNode(listOf(TextNode("link text").setRange(4, 13)), "**", true, true).setRange(2, 15))).setRange(0, 0)).setRange(0, 37), TextNode(" ").setRange(37, 38), QuotedNode(listOf(TextNode("Title").setRange(39, 44)), QuotedNode.Type.Double).setRange(38, 45))).setRange(0, 45))).setRange(0, 45)), listOf(), listOf(), listOf()).setRange(0, 45)) /* 84 */
                /* @formatter:on */
            )

            if (cleanData) {
                val header = arrayOf(
"markdownInput",
"rootNode"
                )

                printData(data, header)
            }
            return data
        }
    }
}
