

package com.vladsch.idea.multimarkdown.util

import com.vladsch.idea.multimarkdown.printData

// Auto-generated test data from: /Users/vlad/src/MarkdownTest/Readme.md

class MarkdownTest__Readme_md {
    companion object {
        //@Parameterized.Parameters(name = "{index}: filePath = {0}, linkRef = {3}, linkAnchor = {4}")
        @JvmStatic
        fun data(): Collection<Array<Any?>> {

            val cleanData = false
            val data = arrayListOf<Array<Any?>>(
                /* @formatter:off */
                /*      arrayOf<Any?>("fullPath"                              , "linkType"    , "linkText"                         , "linkRef"                                                                , "linkAnchor", "linkTitle", "resolvesLocal"                                                          , "resolvesRemote"                                                         , "linkAddress"                                                            , "multiResolve"   ) */
                /*  0 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::WikiLinkRef , ""                                 , "Wiki Link"                                                              , null        , null       , "Wiki-Link"                                                              , "Wiki-Link"                                                              , "Wiki Link"                                                              , arrayOf<String>()),
                /*  1 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::WikiLinkRef , ""                                 , "Home"                                                                   , null        , null       , "Home"                                                                   , "Home"                                                                   , "Home"                                                                   , arrayOf<String>()),
                /*  2 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "not relative link"                , "https://notchecked"                                                     , null        , null       , null                                                                     , null                                                                     , "https://notchecked"                                                     , arrayOf<String>()),
                /*  3 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "not relative link"                , "http://notchecked"                                                      , null        , null       , null                                                                     , null                                                                     , "http://notchecked"                                                      , arrayOf<String>()),
                /*  4 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "not relative link"                , "ftp://notchecked"                                                       , null        , null       , null                                                                     , null                                                                     , "ftp://notchecked"                                                       , arrayOf<String>()),
                /*  5 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "not relative link"                , "mailto:test@notchecked"                                                 , null        , null       , null                                                                     , null                                                                     , "mailto:test@notchecked"                                                 , arrayOf<String>()),
                /*  6 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "not relative link with anchor"    , "#not-checked"                                                           , null        , null       , "Readme.md"                                                              , "Readme.md"                                                              , "#not-checked"                                                           , arrayOf<String>()),
                /*  7 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Missing Link"                     , "Missing-File"                                                           , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /*  8 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Non Wiki File"                    , "NonWikiFile.md"                                                         , null        , null       , "NonWikiFile.md"                                                         , "NonWikiFile.md"                                                         , "NonWikiFile.md"                                                         , arrayOf<String>()),
                /*  9 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Link to self"                     , "Readme.md"                                                              , null        , null       , "Readme.md"                                                              , "Readme.md"                                                              , "Readme.md"                                                              , arrayOf<String>()),
                /* 10 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Link to self"                     , "Readme.md#test"                                                         , null        , null       , "Readme.md#test"                                                         , "Readme.md#test"                                                         , "Readme.md#test"                                                         , arrayOf<String>()),
                /* 11 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Non Wiki File with anchor"        , "NonWikiFile.md#testing"                                                 , null        , null       , "NonWikiFile.md#testing"                                                 , "NonWikiFile.md#testing"                                                 , "NonWikiFile.md#testing"                                                 , arrayOf<String>()),
                /* 12 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Sub Directory VCS Nested File"    , "SubDirectory/NestedFile.md"                                             , null        , null       , "SubDirectory/NestedFile.md"                                             , "SubDirectory/NestedFile.md"                                             , "SubDirectory/NestedFile.md"                                             , arrayOf<String>()),
                /* 13 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Sub Directory Non VCS Nested File", "SubDirectory/NonVcsNestedFile.md"                                       , null        , null       , "SubDirectory/NonVcsNestedFile.md"                                       , "SubDirectory/NonVcsNestedFile.md"                                       , "SubDirectory/NonVcsNestedFile.md"                                       , arrayOf<String>()),
                /* 14 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Non Wiki File"                    , "nonwikifile.md"                                                         , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 15 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Non Wiki File"                    , "NONWIKIFILE.md"                                                         , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 16 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Sub Directory VCS Nested File"    , "subDirectory/NestedFile.md"                                             , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 17 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Sub Directory Non Vcs Nested File", "subDirectory/NonVcsNestedFile.md"                                       , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 18 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Anchor in Name"                   , "anchor-in-name#5"                                                       , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 19 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Anchor in Name"                   , "anchor-in-name#5.md"                                                    , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 20 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Anchor in Name"                   , "anchor-in-name%235.md"                                                  , null        , null       , "anchor-in-name%235.md"                                                  , "anchor-in-name%235.md"                                                  , "anchor-in-name%235.md"                                                  , arrayOf<String>()),
                /* 21 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Anchor in Name"                   , "anchor-in-name%235.md#5"                                                , null        , null       , "anchor-in-name%235.md#5"                                                , "anchor-in-name%235.md#5"                                                , "anchor-in-name%235.md#5"                                                , arrayOf<String>()),
                /* 22 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::ImageLinkRef, "Translation Manager Screenshot"   , "../../wiki/images/ScreenShot_main.png"                                  , null        , null       , "../../wiki/images/ScreenShot_main.png"                                  , "../../wiki/images/ScreenShot_main.png"                                  , "../../wiki/images/ScreenShot_main.png"                                  , arrayOf<String>()),
                /* 23 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "clone"                            , "github-windows://openRepo/https://github.com/kriasoft/react-starter-kit", null        , null       , "github-windows://openRepo/https://github.com/kriasoft/react-starter-kit", "github-windows://openRepo/https://github.com/kriasoft/react-starter-kit", "github-windows://openRepo/https://github.com/kriasoft/react-starter-kit", arrayOf<String>()),
                /* 24 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "fork"                             , "https://github.com/kriasoft/react-starter-kit/fork"                     , null        , null       , null                                                                     , null                                                                     , "https://github.com/kriasoft/react-starter-kit/fork"                     , arrayOf<String>()),
                /* 25 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Non Wiki File"                    , "NonWikiFile"                                                            , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 26 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Sub Directory VCS Nested File"    , "SubDirectory/NestedFile"                                                , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 27 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Non Wiki File"                    , "nonwikifile"                                                            , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 28 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Non Wiki File"                    , "NONWIKIFILe"                                                            , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 29 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Sub Directory VCS Nested File"    , "SubDirectory/NestedFile"                                                , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 30 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Sub Directory Non Vcs Nested File", "SubDirectory/NonVcsNestedFile"                                          , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 31 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Sub Directory Nested File"        , "NestedFile"                                                             , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 32 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Graphs"                           , "../../graphs"                                                           , null        , null       , "../../graphs"                                                           , "../../graphs"                                                           , "../../graphs"                                                           , arrayOf<String>()),
                /* 33 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Issues"                           , "../../issues"                                                           , null        , null       , "../../issues"                                                           , "../../issues"                                                           , "../../issues"                                                           , arrayOf<String>()),
                /* 34 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Pulls"                            , "../../pulls"                                                            , null        , null       , "../../pulls"                                                            , "../../pulls"                                                            , "../../pulls"                                                            , arrayOf<String>()),
                /* 35 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Pulse"                            , "../../pulse"                                                            , null        , null       , "../../pulse"                                                            , "../../pulse"                                                            , "../../pulse"                                                            , arrayOf<String>()),
                /* 36 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Wiki"                             , "../../wiki"                                                             , null        , null       , "../../wiki"                                                             , "../../wiki"                                                             , "../../wiki"                                                             , arrayOf<String>()),
                /* 37 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Wiki Home"                        , "../../wiki/Home"                                                        , null        , null       , "../../wiki/Home"                                                        , "../../wiki/Home"                                                        , "../../wiki/Home"                                                        , arrayOf<String>()),
                /* 38 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Wiki Home"                        , "../../wiki/Home#test"                                                   , null        , null       , "../../wiki/Home#test"                                                   , "../../wiki/Home#test"                                                   , "../../wiki/Home#test"                                                   , arrayOf<String>()),
                /* 39 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Wiki Home"                        , "../../wiki/normal-file"                                                 , null        , null       , "../../wiki/normal-file"                                                 , "../../wiki/normal-file"                                                 , "../../wiki/normal-file"                                                 , arrayOf<String>()),
                /* 40 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Wiki Home"                        , "../../wiki/normal-file#test"                                            , null        , null       , "../../wiki/normal-file#test"                                            , "../../wiki/normal-file#test"                                            , "../../wiki/normal-file#test"                                            , arrayOf<String>()),
                /* 41 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Wiki Home"                        , "../../wiki/SubDirectory/Home.md"                                        , null        , null       , "../../wiki/SubDirectory/Home.md"                                        , "../../wiki/SubDirectory/Home.md"                                        , "../../wiki/SubDirectory/Home.md"                                        , arrayOf<String>()),
                /* 42 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "wiki normal file"                 , "../../wiki/normal-file"                                                 , null        , null       , "../../wiki/normal-file"                                                 , "../../wiki/normal-file"                                                 , "../../wiki/normal-file"                                                 , arrayOf<String>()),
                /* 43 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "wiki normal file"                 , "../../wiki/In-Name"                                                     , null        , null       , "../../wiki/In-Name"                                                     , "../../wiki/In-Name"                                                     , "../../wiki/In-Name"                                                     , arrayOf<String>()),
                /* 44 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "wiki normal file"                 , "../../wiki/In-Name.md"                                                  , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 45 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "wiki normal file"                 , "../../wiki/SubDirectory/In-Name.md"                                     , null        , null       , "../../wiki/SubDirectory/In-Name.md"                                     , "../../wiki/SubDirectory/In-Name.md"                                     , "../../wiki/SubDirectory/In-Name.md"                                     , arrayOf<String>()),
                /* 46 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Anchor in Name"                   , "../../wiki/anchor-in-name#5"                                            , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 47 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "Anchor in Name"                   , "../../wiki/anchor-in-name%235"                                          , null        , null       , "../../wiki/anchor-in-name%235"                                          , "../../wiki/anchor-in-name%235"                                          , "../../wiki/anchor-in-name%235"                                          , arrayOf<String>()),
                /* 48 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "normal file"                      , "../../wiki/normal-file"                                                 , null        , null       , "../../wiki/normal-file"                                                 , "../../wiki/normal-file"                                                 , "../../wiki/normal-file"                                                 , arrayOf<String>()),
                /* 49 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "normal file"                      , "../../wiki/normal-file.md"                                              , null        , null       , "../../wiki/normal-file.md"                                              , "../../wiki/normal-file.md"                                              , "../../wiki/normal-file.md"                                              , arrayOf<String>()),
                /* 50 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "wiki normal file"                 , "../../wiki/In-Name.md"                                                  , null        , null       , null                                                                     , null                                                                     , null                                                                     , arrayOf<String>()),
                /* 51 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::FileLinkRef , "wiki normal file"                 , "../../wiki/SubDirectory/In-Name.md"                                     , null        , null       , "../../wiki/SubDirectory/In-Name.md"                                     , "../../wiki/SubDirectory/In-Name.md"                                     , "../../wiki/SubDirectory/In-Name.md"                                     , arrayOf<String>()),
                /* 52 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::ImageLinkRef, "vcs image"                        , "vcs-image.png"                                                          , null        , null       , "vcs-image.png"                                                          , "vcs-image.png"                                                          , "vcs-image.png"                                                          , arrayOf<String>()),
                /* 53 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::ImageLinkRef, "sub dir vcs image"                , "SubDirectory/sub-dir-vcs-image.png"                                     , null        , null       , "SubDirectory/sub-dir-vcs-image.png"                                     , "SubDirectory/sub-dir-vcs-image.png"                                     , "SubDirectory/sub-dir-vcs-image.png"                                     , arrayOf<String>()),
                /* 54 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::ImageLinkRef, "non vcs image"                    , "non-vcs-image.png"                                                      , null        , null       , "non-vcs-image.png"                                                      , "non-vcs-image.png"                                                      , "non-vcs-image.png"                                                      , arrayOf<String>()),
                /* 55 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::ImageLinkRef, "sub dir non vcs image"            , "SubDirectory/sub-dir-non-vcs-image.png"                                 , null        , null       , "SubDirectory/sub-dir-non-vcs-image.png"                                 , "SubDirectory/sub-dir-non-vcs-image.png"                                 , "SubDirectory/sub-dir-non-vcs-image.png"                                 , arrayOf<String>()),
                /* 56 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::ImageLinkRef, "vcs image"                        , "../../wiki/vcs-image.png"                                               , null        , null       , "../../wiki/vcs-image.png"                                               , "../../wiki/vcs-image.png"                                               , "../../wiki/vcs-image.png"                                               , arrayOf<String>()),
                /* 57 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::ImageLinkRef, "sub dir vcs image"                , "../../wiki/SubDirectory/sub-dir-vcs-image.png"                          , null        , null       , "../../wiki/SubDirectory/sub-dir-vcs-image.png"                          , "../../wiki/SubDirectory/sub-dir-vcs-image.png"                          , "../../wiki/SubDirectory/sub-dir-vcs-image.png"                          , arrayOf<String>()),
                /* 58 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::ImageLinkRef, "non vcs image"                    , "../../wiki/non-vcs-image.png"                                           , null        , null       , "../../wiki/non-vcs-image.png"                                           , "../../wiki/non-vcs-image.png"                                           , "../../wiki/non-vcs-image.png"                                           , arrayOf<String>()),
                /* 59 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/Readme.md", ::ImageLinkRef, "sub dir non vcs image"            , "../../wiki/SubDirectory/sub-dir-non-vcs-image.png"                      , null        , null       , "../../wiki/SubDirectory/sub-dir-non-vcs-image.png"                      , "../../wiki/SubDirectory/sub-dir-non-vcs-image.png"                      , "../../wiki/SubDirectory/sub-dir-non-vcs-image.png"                      , arrayOf<String>())
                /* @formatter:on */
            )

            if (cleanData) {
                val header = arrayOf(
                        "fullPath",
                        "linkType",
                        "linkText",
                        "linkRef",
                        "linkAnchor",
                        "linkTitle",
                        "resolvesLocal",
                        "resolvesExternal",
                        "linkAddress",
                        "multiResolve"
                )

                printData(data, header)
            }
            return data
        }
    }
}
