

package com.vladsch.idea.multimarkdown.util

import com.vladsch.idea.multimarkdown.printData

// Auto-generated test data from: /Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md

class MarkdownTest__MarkdownTest_wiki__normal_file_md {
    companion object {
        //@Parameterized.Parameters(name = "{index}: filePath = {0}, linkRef = {3}, linkAnchor = {4}")
        @JvmStatic
        fun data(): Collection<Array<Any?>> {

            val cleanData = false
            val data = arrayListOf<Array<Any?>>(
                /* @formatter:off */
                /*      arrayOf<Any?>("fullPath"                                                     , "linkType"    , "linkText"              , "linkRef"                                    , "linkAnchor", "linkTitle", "resolvesLocal"                              , "resolvesRemote"                             , "linkAddress"                                , "multiResolve"   ) */
                /*  0 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "Missing File"                               , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /*  1 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "normal file"                                , null        , null       , "normal-file"                                , "normal-file"                                , "normal file"                                , arrayOf<String>()),
                /*  2 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "Non Vcs Page"                               , null        , null       , "Non-Vcs-Page"                               , null                                         , "Non Vcs Page"                               , arrayOf<String>()),
                /*  3 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "normal file#5"                              , null        , null       , "normal-file#5"                              , "normal-file#5"                              , "normal file#5"                              , arrayOf<String>()),
                /*  4 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , "A Normal File"         , "normal file"                                , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /*  5 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , "In Name"               , "normal file"                                , null        , null       , "normal-file"                                , "normal-file"                                , "normal file"                                , arrayOf<String>()),
                /*  6 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "normal file.md"                             , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /*  7 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "normal file.mkd"                            , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /*  8 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "normal file.markdown"                       , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /*  9 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "normal file.mdk"                            , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 10 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "File In Subdirectory"                       , null        , null       , "File-In-Subdirectory"                       , "File-In-Subdirectory"                       , "File In Subdirectory"                       , arrayOf<String>()),
                /* 11 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , "Normal File Text"      , "normal file"                                , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 12 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "anchor in name#5"                           , null        , null       , "anchor-in-name#5"                           , "anchor-in-name#5"                           , "anchor in name#5"                           , arrayOf<String>()),
                /* 13 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "anchor in name#5#5"                         , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 14 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "Space In Name"                              , null        , null       , "Space-In-Name"                              , "Space-In-Name"                              , "Space In Name"                              , arrayOf<String>()),
                /* 15 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "Space In Name#5"                            , null        , null       , "Space-In-Name#5"                            , "Space-In-Name#5"                            , "Space In Name#5"                            , arrayOf<String>()),
                /* 16 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "Normal File"                                , null        , null       , "Normal-File"                                , "Normal-File"                                , "Normal File"                                , arrayOf<String>()),
                /* 17 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "normal-file"                                , null        , null       , "normal-file"                                , "normal-file"                                , "normal-file"                                , arrayOf<String>()),
                /* 18 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "Normal-File"                                , null        , null       , "Normal-File"                                , "Normal-File"                                , "Normal-File"                                , arrayOf<String>()),
                /* 19 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "SubDirectory/In Name"                       , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 20 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "Multiple Match"                             , null        , null       , "Multiple-Match"                             , "Multiple-Match"                             , "Multiple Match"                             , arrayOf<String>()),
                /* 21 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "../../NonWikiFile"                          , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 22 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "Not Wiki Ext"                               , null        , null       , "Not-Wiki-Ext"                               , "Not-Wiki-Ext"                               , "Not Wiki Ext"                               , arrayOf<String>()),
                /* 23 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , ""                      , "Not Wiki Ext 2"                             , null        , null       , "Not-Wiki-Ext-2"                             , "Not-Wiki-Ext-2"                             , "Not Wiki Ext 2"                             , arrayOf<String>()),
                /* 24 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , "normal file"           , "Normal File Text"                           , null        , null       , "Normal-File-Text"                           , "Normal-File-Text"                           , "Normal File Text"                           , arrayOf<String>()),
                /* 25 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , "normal file"           , "normal file"                                , null        , null       , "normal-file"                                , "normal-file"                                , "normal file"                                , arrayOf<String>()),
                /* 26 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::WikiLinkRef , "normal file"           , "Normal File"                                , null        , null       , "Normal-File"                                , "Normal-File"                                , "Normal File"                                , arrayOf<String>()),
                /* 27 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "not relative link"     , "https://notchecked"                         , null        , null       , null                                         , null                                         , "https://notchecked"                         , arrayOf<String>()),
                /* 28 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "not relative link"     , "http://notchecked"                          , null        , null       , null                                         , null                                         , "http://notchecked"                          , arrayOf<String>()),
                /* 29 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "not relative link"     , "ftp://notchecked"                           , null        , null       , null                                         , null                                         , "ftp://notchecked"                           , arrayOf<String>()),
                /* 30 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "not relative link"     , "mailto://notchecked"                        , null        , null       , null                                         , null                                         , "mailto://notchecked"                        , arrayOf<String>()),
                /* 31 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Missing Link"          , "Missing-File"                               , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 32 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "normal file"           , "normal-file"                                , null        , null       , "normal-file"                                , "normal-file"                                , "normal-file"                                , arrayOf<String>()),
                /* 33 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "normal file"           , "normal-file#3"                              , null        , null       , "normal-file#3"                              , "normal-file#3"                              , "normal-file#3"                              , arrayOf<String>()),
                /* 34 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "normal file.md"        , "normal-file.md"                             , null        , null       , "normal-file.md"                             , "normal-file.md"                             , "normal-file.md"                             , arrayOf<String>()),
                /* 35 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Test.kt"               , "Test.kt"                                    , null        , null       , "Test.kt"                                    , "Test.kt"                                    , "Test.kt"                                    , arrayOf<String>()),
                /* 36 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Sub Directory Sub Test", "SubDirectory/Sub-Test.kt"                   , null        , null       , "SubDirectory/Sub-Test.kt"                   , "SubDirectory/Sub-Test.kt"                   , "SubDirectory/Sub-Test.kt"                   , arrayOf<String>()),
                /* 37 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Test.kt"               , "wiki/Test.kt"                               , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 38 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Sub Directory Sub Test", "wiki/SubDirectory/Sub-Test.kt"              , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 39 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "normal file.md"        , "normal-file.md#33"                          , null        , null       , "normal-file.md#33"                          , "normal-file.md#33"                          , "normal-file.md#33"                          , arrayOf<String>()),
                /* 40 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Normal File"           , "normal-file"                                , null        , null       , "normal-file"                                , "normal-file"                                , "normal-file"                                , arrayOf<String>()),
                /* 41 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "anchor in name#5"      , "anchor-in-name#5"                           , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 42 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "anchor in name#5"      , "anchor-in-name#5.md"                        , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 43 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "anchor in name%235"    , "anchor-in-name%235"                         , null        , null       , "anchor-in-name%235"                         , "anchor-in-name%235"                         , "anchor-in-name%235"                         , arrayOf<String>()),
                /* 44 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "anchor in name%23#5"   , "anchor-in-name%235#5"                       , null        , null       , "anchor-in-name%235#5"                       , "anchor-in-name%235#5"                       , "anchor-in-name%235#5"                       , arrayOf<String>()),
                /* 45 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Normal File"           , "normal-file"                                , null        , null       , "normal-file"                                , "normal-file"                                , "normal-file"                                , arrayOf<String>()),
                /* 46 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Normal File"           , "normal-file"                                , null        , null       , "normal-file"                                , "normal-file"                                , "normal-file"                                , arrayOf<String>()),
                /* 47 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Not Wiki Ext"          , "Not-Wiki-Ext"                               , null        , null       , "Not-Wiki-Ext"                               , "Not-Wiki-Ext"                               , "Not-Wiki-Ext"                               , arrayOf<String>()),
                /* 48 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Not Wiki Ext 2"        , "Not-Wiki-Ext-2"                             , null        , null       , "Not-Wiki-Ext-2"                             , "Not-Wiki-Ext-2"                             , "Not-Wiki-Ext-2"                             , arrayOf<String>()),
                /* 49 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Wiki File"             , "In-Name"                                    , null        , null       , "In-Name"                                    , "In-Name"                                    , "In-Name"                                    , arrayOf<String>()),
                /* 50 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Wiki File"             , "In-Name.md"                                 , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 51 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Wiki File"             , "SubDirectory/In-Name"                       , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 52 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Wiki File"             , "SubDirectory/In-Name.md"                    , null        , null       , "SubDirectory/In-Name.md"                    , "SubDirectory/In-Name.md"                    , "SubDirectory/In-Name.md"                    , arrayOf<String>()),
                /* 53 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Wiki File"             , "SubDirectory/Multiple-Match"                , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 54 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Wiki File"             , "Multiple-Match"                             , null        , null       , "Multiple-Match"                             , "Multiple-Match"                             , "Multiple-Match"                             , arrayOf<String>()),
                /* 55 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "File In Subdirectory"  , "File-In-Subdirectory"                       , null        , null       , "File-In-Subdirectory"                       , "File-In-Subdirectory"                       , "File-In-Subdirectory"                       , arrayOf<String>()),
                /* 56 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Non Wiki File"         , "../NonWikiFile"                             , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 57 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Non Wiki File"         , "../blob/master/NonWikiFile.md"              , null        , null       , "../blob/master/NonWikiFile.md"              , "../blob/master/NonWikiFile.md"              , "../blob/master/NonWikiFile.md"              , arrayOf<String>()),
                /* 58 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::FileLinkRef , "Non Wiki File"         , "../blob/master/nonwikiFile.md"              , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 59 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::ImageLinkRef, "vcs image"             , "wiki/vcs-image.png"                         , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 60 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::ImageLinkRef, "sub dir vcs image"     , "wiki/SubDirectory/sub-dir-vcs-image.png"    , null        , null       , null                                         , null                                         , null                                         , arrayOf<String>()),
                /* 61 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::ImageLinkRef, "vcs image"             , "vcs-image.png"                              , null        , null       , "vcs-image.png"                              , "vcs-image.png"                              , "vcs-image.png"                              , arrayOf<String>()),
                /* 62 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::ImageLinkRef, "sub dir vcs image"     , "SubDirectory/sub-dir-vcs-image.png"         , null        , null       , "SubDirectory/sub-dir-vcs-image.png"         , "SubDirectory/sub-dir-vcs-image.png"         , "SubDirectory/sub-dir-vcs-image.png"         , arrayOf<String>()),
                /* 63 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::ImageLinkRef, "non vcs image"         , "wiki/non-vcs-image.png"                     , null        , null       , "wiki/non-vcs-image.png"                     , "wiki/non-vcs-image.png"                     , "wiki/non-vcs-image.png"                     , arrayOf<String>()),
                /* 64 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/normal-file.md", ::ImageLinkRef, "sub dir non vcs image" , "wiki/SubDirectory/sub-dir-non-vcs-image.png", null        , null       , "wiki/SubDirectory/sub-dir-non-vcs-image.png", "wiki/SubDirectory/sub-dir-non-vcs-image.png", "wiki/SubDirectory/sub-dir-non-vcs-image.png", arrayOf<String>())
                /* @formatter:on */
            )

            if (cleanData) {
                val header = arrayOf(
                        "fullPath",
                        "linkType",
                        "linkText",
                        "linkRef",
                        "linkAnchor",
                        "linkTitle",
                        "resolvesLocal",
                        "resolvesExternal",
                        "linkAddress",
                        "multiResolve"
                )

                printData(data, header)
            }
            return data
        }
    }
}
