

/*
 * Copyright (c) 2015-2015 Vladimir Schneider <vladimir.schneider@gmail.com>, all rights reserved.
 *
 * This code is private property of the copyright holder and cannot be used without
 * having obtained a license or prior written permission of the of the copyright holder.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */
package com.vladsch.idea.multimarkdown.util

import com.vladsch.idea.multimarkdown.printData

// Auto-generated test data from: /Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md

class MarkdownTest__MarkdownTest_wiki__Home_md {
    companion object {
        //@Parameterized.Parameters(name = "{index}: filePath = {0}, linkRef = {3}, linkAnchor = {4}")
        @JvmStatic
        fun data(): Collection<Array<Any?>> {

            val cleanData = true
            val data = arrayListOf<Array<Any?>>(
                /* @formatter:off */
                /*      arrayOf<Any?>("fullPath"                                              , "linkType"    , "linkText"              , "linkRef"                                    , "linkAnchor", "linkTitle", "resolvesLocal"                              , "resolvesExternal"                       , "linkAddress"                                , "multiResolve"                                                                                                         ) */
                /*  0 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "Missing File"                               , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>()                                                                                                      ),
                /*  1 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "normal file"                                , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal file"                                , arrayOf<String>()                                                                                                      ),
                /*  2 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "Non Vcs Page"                               , null        , null       , "Non-Vcs-Page.md"                       , "Non-Vcs-Page.md"                     , "Non Vcs Page"                               , arrayOf<String>()                                                                                                      ),
                /*  3 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "normal file"                                , "5"         , null       , "normal-file.md"                        , "normal-file.md"                      , "normal file"                                , arrayOf<String>()                                                                                                      ),
                /*  4 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , "normal file"           , "A Normal File"                              , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>()                                                                                                      ),
                /*  5 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , "normal file"           , "In Name"                                    , null        , null       , "SubDirectory/In-Name.md"               , "SubDirectory/In-Name.md"             , "In Name"                                    , arrayOf<String>()                                                                                                      ),
                /*  6 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "normal file.md"                             , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>("normal-file.md")                                                                                      ),
                /*  7 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "normal file.mkd"                            , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>("normal-file.md")                                                                                      ),
                /*  8 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "normal file.markdown"                       , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>("normal-file.md")                                                                                      ),
                /*  9 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "normal file.mdk"                            , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>("normal-file.md")                                                                                      ),
                /* 10 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "File In Subdirectory"                       , null        , null       , "SubDirectory/File-In-Subdirectory.md"  , "SubDirectory/File-In-Subdirectory.md", "File In Subdirectory"                       , arrayOf<String>()                                                                                                      ),
                /* 11 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , "Normal File Text"      , "normal file"                                , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal file"                                , arrayOf<String>("normal-file.md")                                                                                      ),
                /* 12 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "anchor in name"                             , "5"         , null       , "anchor-in-name#5.md"                   , "anchor-in-name#5.md"                 , "anchor in name#5"                           , arrayOf<String>()                                                                                                      ),
                /* 13 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "anchor in name"                             , "5#5"       , null       , null                                    , null                                  , null                                         , arrayOf<String>()                                                                                                      ),
                /* 14 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "Space In Name"                              , null        , null       , "Space In Name.md"                      , "Space In Name.md"                    , "Space In Name"                              , arrayOf<String>()                                                                                                      ),
                /* 15 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "Space In Name"                              , "5"         , null       , "Space In Name.md"                      , "Space In Name.md"                    , "Space In Name"                              , arrayOf<String>()                                                                                                      ),
                /* 16 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "Normal File"                                , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal file"                                , arrayOf<String>()                                                                                                      ),
                /* 17 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "normal-file"                                , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal file"                                , arrayOf<String>()                                                                                                      ),
                /* 18 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "Normal-File"                                , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal file"                                , arrayOf<String>()                                                                                                      ),
                /* 19 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "Multiple Match"                             , null        , null       , "Multiple-Match.markdown"               , "Multiple-Match.markdown"             , "Multiple Match"                             , arrayOf<String>("Multiple-Match.markdown", "Multiple-Match.md", "Multiple-Match.mkd", "SubDirectory/Multiple-Match.md")),
                /* 20 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "../../NonWikiFile"                          , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>()                                                                                                      ),
                /* 21 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "Not Wiki Ext"                               , null        , null       , "Not-Wiki-Ext.mkd"                      , "Not-Wiki-Ext.mkd"                    , "Not Wiki Ext"                               , arrayOf<String>()                                                                                                      ),
                /* 22 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , ""                      , "Not Wiki Ext 2"                             , null        , null       , "Not-Wiki-Ext-2.markdown"               , "Not-Wiki-Ext-2.markdown"             , "Not Wiki Ext 2"                             , arrayOf<String>()                                                                                                      ),
                /* 23 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , "Normal File Text"      , "normal file"                                , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal file"                                , arrayOf<String>()                                                                                                      ),
                /* 24 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , "normal file"           , "normal file"                                , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal file"                                , arrayOf<String>()                                                                                                      ),
                /* 25 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , "Normal File"           , "normal file"                                , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal file"                                , arrayOf<String>()                                                                                                      ),
                /* 26 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::WikiLinkRef , "normal file"           , "Normal File"                                , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal file"                                , arrayOf<String>()                                                                                                      ),
                /* 27 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "not relative link"     , "https://notchecked"                         , null        , null       , null                                    , null                                  , "https://notchecked"                         , arrayOf<String>()                                                                                                      ),
                /* 28 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "not relative link"     , "http://notchecked"                          , null        , null       , null                                    , null                                  , "http://notchecked"                          , arrayOf<String>()                                                                                                      ),
                /* 29 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "not relative link"     , "ftp://notchecked"                           , null        , null       , null                                    , null                                  , "ftp://notchecked"                           , arrayOf<String>()                                                                                                      ),
                /* 30 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "not relative link"     , "mailto://notchecked"                        , null        , null       , null                                    , null                                  , "mailto://notchecked"                        , arrayOf<String>()                                                                                                      ),
                /* 31 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Missing Link"          , "Missing-File"                               , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>()                                                                                                      ),
                /* 32 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "normal file"           , "normal-file"                                , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal-file"                                , arrayOf<String>()                                                                                                      ),
                /* 33 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "normal file"           , "normal-file"                                , "3"         , null       , "normal-file.md"                        , "normal-file.md"                      , "normal-file"                                , arrayOf<String>()                                                                                                      ),
                /* 34 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "normal file.md"        , "normal-file.md"                             , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal-file.md"                             , arrayOf<String>()                                                                                                      ),
                /* 35 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Test.kt"               , "Test.kt"                                    , null        , null       , "Test.kt"                               , "Test.kt"                             , "Test.kt"                                    , arrayOf<String>()                                                                                                      ),
                /* 36 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Sub Directory Sub Test", "SubDirectory/Sub-Test.kt"                   , null        , null       , "SubDirectory/Sub-Test.kt"              , "SubDirectory/Sub-Test.kt"            , "SubDirectory/Sub-Test.kt"                   , arrayOf<String>()                                                                                                      ),
                /* 37 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Test.kt"               , "wiki/Test.kt"                               , null        , null       , "wiki/Test.kt"                          , "wiki/Test.kt"                        , "wiki/Test.kt"                               , arrayOf<String>()                                                                                                      ),
                /* 38 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Sub Directory Sub Test", "wiki/SubDirectory/Sub-Test.kt"              , null        , null       , "wiki/SubDirectory/Sub-Test.kt"         , "wiki/SubDirectory/Sub-Test.kt"       , "wiki/SubDirectory/Sub-Test.kt"              , arrayOf<String>()                                                                                                      ),
                /* 39 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "normal file.md"        , "normal-file.md#33"                          , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal-file.md"                             , arrayOf<String>()                                                                                                      ),
                /* 40 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Normal File"           , "normal-file"                                , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal-file"                                , arrayOf<String>()                                                                                                      ),
                /* 41 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "anchor in name#5"      , "anchor-in-name"                             , "5"         , null       , "anchor-in-name#5.md"                   , "anchor-in-name#5.md"                 , "anchor-in-name#5"                           , arrayOf<String>()                                                                                                      ),
                /* 42 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "anchor in name#5"      , "anchor-in-name"                             , "5.md"      , null       , "anchor-in-name#5.md"                   , "anchor-in-name#5.md"                 , "anchor-in-name#5.md"                        , arrayOf<String>()                                                                                                      ),
                /* 43 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "anchor in name%235"    , "anchor-in-name%235"                         , null        , null       , "anchor-in-name#5.md"                   , "anchor-in-name#5.md"                 , "anchor-in-name#5"                           , arrayOf<String>()                                                                                                      ),
                /* 44 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "anchor in name%23#5"   , "anchor-in-name%235"                         , "5"         , null       , "anchor-in-name#5.md"                   , "anchor-in-name#5.md"                 , "anchor-in-name#5"                           , arrayOf<String>()                                                                                                      ),
                /* 45 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Normal File"           , "normal-file"                                , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal-file"                                , arrayOf<String>()                                                                                                      ),
                /* 46 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Normal File"           , "normal-file"                                , null        , null       , "normal-file.md"                        , "normal-file.md"                      , "normal-file"                                , arrayOf<String>()                                                                                                      ),
                /* 47 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Not Wiki Ext"          , "Not-Wiki-Ext"                               , null        , null       , "Not-Wiki-Ext.mkd"                      , "Not-Wiki-Ext.mkd"                    , "Not-Wiki-Ext"                               , arrayOf<String>()                                                                                                      ),
                /* 48 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Not Wiki Ext 2"        , "Not-Wiki-Ext-2"                             , null        , null       , "Not-Wiki-Ext-2.markdown"               , "Not-Wiki-Ext-2.markdown"             , "Not-Wiki-Ext-2"                             , arrayOf<String>()                                                                                                      ),
                /* 49 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Wiki File"             , "In-Name"                                    , null        , null       , "SubDirectory/In-Name.md"               , "SubDirectory/In-Name.md"             , "In-Name"                                    , arrayOf<String>()                                                                                                      ),
                /* 50 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Wiki File"             , "In-Name.md"                                 , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>()                                                                                                      ),
                /* 51 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Wiki File"             , "SubDirectory/In-Name"                       , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>("SubDirectory/In-Name.md")                                                                             ),
                /* 52 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Wiki File"             , "SubDirectory/In-Name.md"                    , null        , null       , "SubDirectory/In-Name.md"               , "SubDirectory/In-Name.md"             , "SubDirectory/In-Name.md"                    , arrayOf<String>()                                                                                                      ),
                /* 53 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Wiki File"             , "SubDirectory/Multiple-Match"                , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>("SubDirectory/Multiple-Match.markdown")                                                                ),
                /* 54 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Wiki File"             , "Multiple-Match"                             , null        , null       , "Multiple-Match.markdown"               , "Multiple-Match.markdown"             , "Multiple-Match"                             , arrayOf<String>("Multiple-Match.markdown", "Multiple-Match.md", "Multiple-Match.mkd", "SubDirectory/Multiple-Match.md")),
                /* 55 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "File In Subdirectory"  , "File-In-Subdirectory"                       , null        , null       , "SubDirectory/File-In-Subdirectory.md"  , "SubDirectory/File-In-Subdirectory.md", "File-In-Subdirectory"                       , arrayOf<String>()                                                                                                      ),
                /* 56 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Non Wiki File"         , "../NonWikiFile"                             , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>("../NonWikiFile.md")                                                                                   ),
                /* 57 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Non Wiki File"         , "../blob/master/NonWikiFile.md"              , null        , null       , "../NonWikiFile.md"                     , "../NonWikiFile.md"                   , "../blob/master/NonWikiFile.md"              , arrayOf<String>()                                                                                                      ),
                /* 58 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::FileLinkRef , "Non Wiki File"         , "../blob/master/nonwikiFile.md"              , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>("../NonWikiFile.md")                                                                                   ),
                /* 59 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::ImageLinkRef, "vcs image"             , "wiki/vcs-image.png"                         , null        , null       , "vcs-image.png"                         , "vcs-image.png"                       , "wiki/vcs-image.png"                         , arrayOf<String>("vcs-image.png")                                                                                       ),
                /* 60 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::ImageLinkRef, "sub dir vcs image"     , "wiki/SubDirectory/sub-dir-vcs-image.png"    , null        , null       , "SubDirectory/sub-dir-vcs-image.png"    , "SubDirectory/sub-dir-vcs-image.png"  , "wiki/SubDirectory/sub-dir-vcs-image.png"    , arrayOf<String>()                                                                                                      ),
                /* 61 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::ImageLinkRef, "vcs image"             , "vcs-image.png"                              , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>()                                                                                                      ),
                /* 62 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::ImageLinkRef, "sub dir vcs image"     , "SubDirectory/sub-dir-vcs-image.png"         , null        , null       , null                                    , null                                  , null                                         , arrayOf<String>()                                                                                                      ),
                /* 63 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::ImageLinkRef, "non vcs image"         , "wiki/non-vcs-image.png"                     , null        , null       , "non-vcs-image.png"                     , "non-vcs-image.png"                   , "wiki/non-vcs-image.png"                     , arrayOf<String>()                                                                                                      ),
                /* 64 */arrayOf<Any?>("/Users/vlad/src/MarkdownTest/MarkdownTest.wiki/Home.md", ::ImageLinkRef, "sub dir non vcs image" , "wiki/SubDirectory/sub-dir-non-vcs-image.png", null        , null       , "SubDirectory/sub-dir-non-vcs-image.png", null                                  , "wiki/SubDirectory/sub-dir-non-vcs-image.png", arrayOf<String>()                                                                                                      )
                /* @formatter:on */
            )

            if (cleanData) {
                val header = arrayOf(
                        "fullPath",
                        "linkType",
                        "linkText",
                        "linkRef",
                        "linkAnchor",
                        "linkTitle",
                        "resolvesLocal",
                        "resolvesExternal",
                        "linkAddress",
                        "multiResolve"
                )

                printData(data, header)
            }
            return data
        }
    }
}
